#site settings
title: "Prismatica"
subtitle: "LGBTQ Fantasy and Science Fiction Magazine"
description: "LGBTQ Fantasy and Science Fiction Magazine"
baseurl: "/"
url: "http://prismaticamagazine.com/"
email: "prismatica.mag@gmail.com"
avatar: ""
cover: "assets/prismatica-banner-small.png"
logo: "assets/logo.png"
  

#build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

    
 # Google analytics
# ga_tracking_id: ""

# Category descriptions (for archive pages)
descriptions:
  - cat: fiction
    desc: "Short stories."

  - cat: art
    desc: "Artwork"

social:
  - name: GitHub
    icon: github
    username: lazyadveturerpublishing
    url: https://github.com/lazyadventurerpublishing
    desc: Fork me on GitHub
    share: false

  
  - name: Tumblr
    icon: tumblr
    username: prismaticamagazine
    url: https://prismaticamagazine.tumblr.com
    desc: Follow me on Tumblr
    share: false
    
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

